# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d292b81ca81f9c2cb3db1ee82a03077f5d85b14e5f76098ff897112ac2b70f59f3475ac7b204e8b2fa752071a5682904384d7519ca9214293840d821de8dfce

test:
  secret_key_base: 40c2ba5b1fc0856d7f85721776b2092de69548d9c82c3bbcd714bd52666eb5d7c1587c37fcbfc973c65a075f8fcc8227b1e98346feda215ceb6aeb93db2d8d37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
